version: 1.0.{build}
image: Ubuntu1804
test: off
deploy:
- provider: FTP
  host: 165.227.87.165
  protocol: sftp
  username: root
  password: 3qmxzsDBC#e&74Z
    secure: F5QxSRIRsOPhiyLCVoJRjA==

environment:
  my_variable:
    secure: W100DW99ykVZNQ+Rx1HM5g==

  my_variable2:
    secure: 4fOvO3IUXSNCKmNCMBSYNw==
