version: 1.0.{build}
image: Ubuntu1804
test: off
deploy:
- provider: SFTP
  host: 
    secure: ZDYooCiUAomCBwZ+71Xgew==
  protocol: sftp
  username: 
    secure: Aory6UFezi0fpuwaf/ucCw==
  password:
    secure: 40zj86TZBM2gnrfJR6tWqg==
  folder: /var/www/Site1/htdocs/RepeaterWarning
  on:
    branch: main
